[profile.ci.fuzz]
runs = 10_000
[rpc_endpoints]
mumbai = "${MUMBAI_RPC_URL}"
polygon = "${POLYGON_RPC_URL}"
[etherscan]
polygon = { key = "${POLYGONSCAN_API_KEY}" }
[default]
libraries = ["src/lib/Poseidon.sol:PoseidonUnit6L:0xb588b8f07012Dc958aa90EFc7d3CF943057F17d7","src/lib/SpongePoseidon.sol:SpongePoseidon:0x12d8C87A61dAa6DD31d8196187cFa37d1C647153"]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config